name: Digilock
main: com.almuramc.digilock.Digilock
author: Dockter
authors: [Rocologo, Dockter, Zidane]
website: http://dev.bukkit.org/server-mods/digilock/
description: Protection of blocks using the digilock system including Spout GUI support.
version: 1.3
depend: [Spout]
softdepend: [Vault, WorldGuard, MobArena, Jail, War, Residence]

permissions:
    digilock.admin:
        default: op
    digilock.signedit:
        default: op
    digilock.create:
        default: op
    digilock.use:
        default: op



