name: Digilock
main: com.almuramc.digilock.Digilock
author: Rocologo
authors: [Rocologo, Dockter]
website: http://dev.bukkit.org/server-mods/digilock/
description: Protection of blocks using the digilock system including Spout GUI support.
version: 1.0
depend: [Spout]
softdepend: [Vault, WorldGuard, MobArena, Jail, War, Residence]
commands:
    digilock:
        description: Admin commands.
        usage: /digilock [reload]
        permission: digilock.admin
    lock:
        description: Lock the item with a digital pincode.
        usage: /lock [pincode]|[unlock pincode]|[lock pincode]|[owner playername]|[closetimer seconds]|[usecost cost]|[remove]|[addcoowner name]|[remcoowner name]|[adduser name]|[remuser name]|[info]
        aliases: dlock
        permission: digilock.lock.use
permissions:
    digilock.admin:
        default: op
    digilock.signedit:
        default: op
    digilock.create:
        default: op
    digilock.use:
        default: op
    digilock.admin:
        default: op



